
version: '3'

volumes:
  node_modules:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    environment:
      - npm_config_cache=/app/.npm_cache

    volumes:
      - ./:/app
      - node_modules/:/app/node_modules/

  extensioner:
    build: .

    environment:
      - npm_config_cache=/app/.npm_cache

    entrypoint: npm start
